### PR TITLE
Fix URI resolving when dataset URI contains a dot

### PR DESCRIPTION
**Pull request by erikap**
When a dataset URI contains a dot in the collection or resource name, a 404 is returned when retrieving the dataset. Parts of the URI are transformed to uppercase during URI processing, but they aren't reverted to lowercase afterwards causing a 404.

### CODE REVIEW

**Comment by coreation** [comment]
Thanks! (The addition KML bug was already patched though :) )

**Comment by erikap** [comment]
Will this fix be released in TDT 6.0?

**Comment by coreation** [comment]
The development branch will get integrated entirely in the master in december, which marks the 6.0 release, so yes ;).

**Comment by erikap** [comment]
Ok, thanks!

**Pull request merged**
