### PR TITLE
Make GEOJSONFormatter php-5.4 compatible.

### PR DESCRIPTION
**Pull request by DieterDePaepe**

### CODE REVIEW

**Comment by coreation** [comment]
Since of recent, I'm thinking about throwing away the map_property field and get all of the info in there. 

1/ It limits the data that is shown on a map to 1, which can be annoying.
2/ It mostly confuses people that add a CSV file or SHP file about what the property actually does.

2/ isn't really an issue, it's about finding the most layman term to address what map property did. 1/ However is an issue. So I'm likely to delete the property, any thoughts? Sorry to not have this communicated, but it's an idea I've just played with recently.

**Comment by DieterDePaepe** [comment]
1) This is a matter of visualisation. I would expect a map to display all data if the item is selected, if it does not, that's a problem on the side of the map. The "id" attribute is part of the GeoJSON spec and has proper uses in my opinion.

2) Agreed, I think this feature isn't all that well documented and may benefit from a clearer name as well.

**Comment by coreation** [comment]
It is a matter of visualisation yes, I see however that the "id" field in the GeoJSON spec is referred to as the following 

```
If a feature has a commonly used identifier, that identifier should be included as a member of the feature object with the name "id".
```
So in that case we could rename it to id (in the front-end) if such a property is present.

**Comment by DieterDePaepe** [comment]
The word "id" makes me think of numbers. My vote is for "identifier" or "feature identifier".

**Comment by DieterDePaepe** [comment]
But in any case, this PR is not about changing behaviour. It's about a specific syntax that is not yet supported in php5.4. I see you already changed that line in 23e108d, but didn't you (accidently?) remove the initialization of the variable there?

**Comment by coreation** [comment]
It's indeed not changing behaviour, merged!

**Pull request merged**
